name: to_do_lists
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  connectivity_plus: ^2.1.3  
  flutter:
    sdk: flutter
  go_router: ^13.1.0
  http: ^1.2.1
  infinite_scroll_pagination: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loading-photo.png
    - assets/no-image.png
    - assets/user.png
